# version: "3.8"

services:
  #API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3010:3010"
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    env_file:
      - ./env/api-gateway.env
    depends_on:
      - auth-service
      - notification-service
    networks:
      - food-ordering-network

  # Auth Service
  auth-service:
    build: ./auth-service
    ports:
      - "3002:3002"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    env_file:
      - ./env/auth-service.env
    networks:
      - food-ordering-network

  # Customer Service
  # customer-service:
  #   build: ./customer-service
  #   ports:
  #     - "3002:3002"
  #   volumes:
  #     - ./customer-service:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./env/customer-service.env
  #   depends_on:
  #     - auth-service

  # Restaurant Service
  # restaurant-service:
  #   build: ./restaurant-service
  #   ports:
  #     - "3003:3003"
  #   volumes:
  #     - ./restaurant-service:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./env/restaurant-service.env
  #   depends_on:
  #     - auth-service

  # Order Service
  order-service:
    build: ./order-service
    ports:
      - "3004:3004"
    volumes:
      - ./order-service:/app
      - /app/node_modules
    env_file:
      - ./env/order-service.env
    depends_on:
      - auth-service
      - customer-service
      - restaurant-service

  # # Delivery Service
  # delivery-service:
  #   build: ./delivery-service
  #   ports:
  #     - "3005:3005"
  #   volumes:
  #     - ./delivery-service:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./env/delivery-service.env
  #   depends_on:
  #     - auth-service
  #     - order-service

  # # Payment Service
  # payment-service:
  #   build: ./payment-service
  #   ports:
  #     - "3006:3006"
  #   volumes:
  #     - ./payment-service:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./env/payment-service.env
  #   depends_on:
  #     - auth-service
  #     - order-service

  # Notification Service
  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    volumes:
      - ./notification-service:/app
      - /app/node_modules
    env_file:
      - ./env/notification-service.env
    depends_on:
      - auth-service
    networks:
      - food-ordering-network

networks:
  food-ordering-network:
    driver: bridge
    name: food-ordering-network
