apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: food-ordering
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: url
            - name: PAYHERE_MERCHANT_ID
              valueFrom:
                secretKeyRef:
                  name: payhere-secret
                  key: merchant_id
            - name: PAYHERE_SECRET
              valueFrom:
                secretKeyRef:
                  name: payhere-secret
                  key: secret
            - name: PAYHERE_MODE
              value: "sandbox"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: food-ordering
spec:
  selector:
    app: payment-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
