apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: food-ordering
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurant-uploads-pvc
  namespace: food-ordering
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
